src/objects/Exception__c.object
<CustomObject>
    <fields>
        <fullName>Exception_Id__c</fullName>
        <label>Exception ID</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <label>Exception Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Line_Number__c</fullName>
        <description>Line Number</description>
        <inlineHelpText>Line Number</inlineHelpText>
        <label>Line Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NumDml__c</fullName>
        <label>Number of Rows Failed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organisation_Id__c</fullName>
        <label>Organisation ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace_String__c</fullName>
        <label>Stack Trace String</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Of_Occurence__c</fullName>
        <label>Time Of Occurence</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Exception</label>
    <nameField>
        <label>Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExceptionDataUtility.cls
public class ExceptionDataUtility {
    public static void createException (Exception e) 
    {
        system.debug('i am here');
        Exception__c exObj = new Exception__c();
        if(e.getTypeName().equals('System.DmlException')) {
            integer num=e.getNumDml();
            exObj.numDML__c=num;  
            for(integer i=0;i<num;i++) {
                system.debug(e.getDmlId(i));
                exObj.Exception_Id__c=exObj.Exception_Id__c+ ', '+e.getDmlId(i);
            }
            exObj.Exception_Id__c=exObj.Exception_Id__c.removeStart('null, ');   
        }
        exObj.Organisation_Id__c=UserInfo.getOrganizationId();
        exObj.Line_Number__c = e.getLineNumber();
        exObj.Name=e.getTypeName() + system.now();
        exObj.Exception_Type__c=e.getTypeName();
        exObj.Message__c=e.getMessage();
        exObj.Time_Of_Occurence__c=System.now();
        exObj.Stack_Trace_String__c=e.getStackTraceString();
        exObj.userId__c = UserInfo.getUserId();
        insert exObj;
    }
}